# <strong><font color='#3399FF'>1. Acerca del Desafío</font></strong> 
---

## <font color='#0066CC'>Contexto</font>
---

El proyecto propone una situación ficticia donde hemos sido contratados como **analistas de datos** para trabajar específicamente en el 'churn' o cancelaciones de clientes de la empresa Telecom X.

## <font color='#0066CC'>Antecedentes</font>
---

Este proyecto es una continuación del proyecto [challenge-telecom-x](https://github.com/carloslozano-rg/challenge-telecom-x.git), en el cual: 
- Realizamos un tratamiento a los datos.
- Desarrollamos un análisis exploratorio.
- Descubrimos algunos insigths importantes. 
- Proporcionamos algunas recomendaciones de como tratar la raíz del problema.

## <font color='#0066CC'>Objetivo</font>
---

La empresa quiere anticiparse al problema de la cancelación, por lo que la misión que nos han asignado es es **desarrollar modelos predictivos** capaces de prever qué clientes tienen mayor probabilidad de cancelar sus servicios.

## <font color='#0066CC'>Conjunto de Datos o Dataset</font>
---

El dataset que vamos a ocupar fue producto del tratamiento de los datos del proyecto [challenge-telecom-x](https://github.com/carloslozano-rg/challenge-telecom-x.git), del DataFrame **telecom_x_estandarizado**, el cual fue convertido a formato csv con el nombre de **'datos_telecom_x.csv'**.

Se realizaron los siguientes tratamientos sobre los datos originales:
- Se eliminaron registros que contenian un carácter vacío en la columna **'cancelacion'**, ya que: 
    - era una columna muy importante para no saber si el cliente había cancelado o no su servicio,
    - y representaban menos del 3% del total.
- Se introdujeron ceros en los registros con un carácter vacío en la columna **'cargo_total'**, ya que representaban a clientes que apenas comenzaban con su servicio.

- Se tradujeron los nombres de varias columnas para mayor claridad.

# <strong><font color='#3399FF'>2. Preparación de los Datos</font></strong> 
---

## <font color='#0066CC'>Extracción de datos tratados</font>
---

### <font color='#003366'>Lectura de Datos</font>
---

Creamos un DataFrame (DF) que contenga la información de los clientes de Telecom X a partir del archivo **'datos_telecom_x.csv'**:

In [1]:
import pandas as pd

In [2]:
telecom_x_df_inicial = pd.read_csv(filepath_or_buffer='datos_telecom_x.csv', sep=',', encoding='UTF-8')
telecom_x_df_inicial.head()

,cliente_id,cancelacion,genero,adulto_mayor,pareja,dependientes,meses_antiguedad,servicio_telefonico,multiples_lineas,servicio_internet,...,proteccion_dispositivos,soporte_tecnologico,streaming_tv,streaming_peliculas,contrato,factura_en_linea,metodo_pago,cargo_mensual,cargo_total,cuentas_diarias
0,0002-ORFBO,0,Femenino,0,1,1,9,1,No,DSL,...,No,Si,Si,No,Un año,1,Cheque por correo,65.6,593.30,2.19
1,0003-MKNFE,0,Masculino,0,0,0,9,1,Si,DSL,...,No,No,No,Si,Por mes,0,Cheque por correo,59.9,542.40,2.00
2,0004-TLHLJ,1,Masculino,0,0,0,4,1,No,Fibra óptica,...,Si,No,No,No,Por mes,1,Cheque electrónico,73.9,280.85,2.46
3,0011-IGKFF,1,Masculino,1,1,0,13,1,No,Fibra óptica,...,Si,No,Si,Si,Por mes,1,Cheque electrónico,98.0,1237.85,3.27
4,0013-EXCHZ,1,Femenino,1,1,0,3,1,No,Fibra óptica,...,No,Si,Si,No,Por mes,1,Cheque por correo,83.9,267.40,2.80

**Aclaración**: en las columnas 'cancelacion', 'adulto_mayor', 'pareja', 'dependientes', 'servicio_telefonico' y 'factura_en_linea':
- 0 = No
- 1 = Si

Analizamos los metadatos del DF y observamos 22 columnas y 7043 registros:

In [3]:
telecom_x_df_inicial.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   cliente_id                7043 non-null   object
 1   cancelacion               7043 non-null   int64
 2   genero                    7043 non-null   object
 3   adulto_mayor              7043 non-null   int64
 4   pareja                    7043 non-null   int64
 5   dependientes              7043 non-null   int64
 6   meses_antiguedad          7043 non-null   int64
 7   servicio_telefonico       7043 non-null   int64
 8   multiples_lineas          7043 non-null   object
 9   servicio_internet         7043 non-null   object
 10  seguridad_en_linea        7043 non-null   object
 11  copia_seguridad_en_linea  7043 non-null   object
 12  proteccion_dispositivos   7043 non-null   object
 13  soporte_tecnologico       7043 non-null   object
 14  streaming_tv              7043 non-null   object
 15  streaming_peliculas       7043 non-null   object
 16  contrato                  7043 non-null   object
 17  factura_en_linea          7043 non-null   int64
 18  metodo_pago               7043 non-null   object
 19  cargo_mensual             7043 non-null   float64
 20  cargo_total               7043 non-null   float64
 21  cuentas_diarias           7043 non-null   float64
dtypes: float64(3), int64(7), object(12)
memory usage: 1.2+ MB

### <font color='#003366'>Estadística Descriptiva</font>
---

Columnas numéricas:

In [4]:
telecom_x_df_inicial.describe()

,cancelacion,adulto_mayor,pareja,dependientes,meses_antiguedad,servicio_telefonico,factura_en_linea,cargo_mensual,cargo_total,cuentas_diarias
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,0.265370,0.162147,0.483033,0.299588,32.371149,0.903166,0.592219,64.761692,2279.734304,2.158675
std,0.441561,0.368612,0.499748,0.458110,24.559481,0.295752,0.491457,30.090047,2266.794470,1.003088
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.250000,0.000000,0.610000
25%,0.000000,0.000000,0.000000,0.000000,9.000000,1.000000,0.000000,35.500000,398.550000,1.180000
50%,0.000000,0.000000,0.000000,0.000000,29.000000,1.000000,1.000000,70.350000,1394.550000,2.340000
75%,1.000000,0.000000,1.000000,1.000000,55.000000,1.000000,1.000000,89.850000,3786.600000,2.990000
max,1.000000,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,118.750000,8684.800000,3.960000

Columnas categóricas:

In [5]:
telecom_x_df_inicial.describe(include='object')

,cliente_id,genero,multiples_lineas,servicio_internet,seguridad_en_linea,copia_seguridad_en_linea,proteccion_dispositivos,soporte_tecnologico,streaming_tv,streaming_peliculas,contrato,metodo_pago
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,3,3,3,3,3,3,3,3,3,4
top,9995-HOTOH,Masculino,No,Fibra óptica,No,No,No,No,No,No,Por mes,Cheque electrónico
freq,1,3555,3390,3096,3498,3088,3095,3473,2810,2785,3875,2365

# <strong><font color='#3399FF'>3. Correlación y Selección de Variables</font></strong> 
---

# <strong><font color='#3399FF'>4. Modelado Predictivo</font></strong> 
---

# <strong><font color='#3399FF'>5. Interpretación y Conclusiones</font></strong> 
---